### ISSUE TITLE
"IndexError: list index out of range" on meta categorization request

### ISSUE THREAD

**Issue by arybchik** [ts-factory/bublik#8]
Jan 15 07:12:30 srv25344 runcelery[227244]: [2024-01-15 07:12:30,072: ERROR/ForkPoolWorker-8] Signal handler <function add_successful_import_task_event at 0x7f22b235f160> raised: IndexError('list index out of range')
Jan 15 07:12:30 srv25344 runcelery[227244]: Traceback (most recent call last):
Jan 15 07:12:30 srv25344 runcelery[227244]:   File "/srv/bublik/private/bublik/.env/lib/python3.9/site-packages/celery/utils/dispatch/signal.py", line 288, in send
Jan 15 07:12:30 srv25344 runcelery[227244]:     response = receiver(signal=self, sender=sender, **named)
Jan 15 07:12:30 srv25344 runcelery[227244]:   File "/srv/bublik/private/bublik/bublik/interfaces/celery/tasks.py", line 74, in add_successful_import_task_event
Jan 15 07:12:30 srv25344 runcelery[227244]:     msg=f'successful {sender.name} {sender.request.args[0]} '
Jan 15 07:12:30 srv25344 runcelery[227244]: IndexError: list index out of range
Jan 15 07:12:30 srv25344 runcelery[227244]: [2024-01-15 07:12:30,072: INFO/ForkPoolWorker-8] Task bublik.interfaces.celery.tasks.meta_categorization[fc10ca2e-83f9-42fa-808d-e5d96ed35ee6] succeeded in 0.08929207921028137s: 'fc10ca2e-83f9-42fa-808d-e5d96ed35ee6'

**Comment by arybchik** [comment]
Fixed in merged in PR
